apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-cache
  namespace: mytenant
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-cache
  minReplicas: 1
  maxReplicas: 2
