apiVersion: v1
kind: Service
metadata:
  name: my-cache
  namespace: mytenant
  labels:
    app: my-cache
spec:
  selector:
    app: my-cache
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  type: ClusterIP
