apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - virtualservice.yaml
  - configmap.yaml
# Omit secret.yaml, infisicalsecret, sealedsecret — add in real repo when needed
