apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-app
  namespace: istio-system
spec:
  gateways:
    - istio-system/istio-ingressgateway
  hosts:
    - example.labci.com
  http:
    - match:
        - uri:
            prefix: "/my-app/"
      rewrite:
        uri: "/"
      route:
        - destination:
            host: my-app.mytenant.svc.cluster.local
            port:
              number: 8080
