
# Root Application: DEV — deploy nginx app only
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
spec:
  project: labci-dev-apps-project
  source:
    repoURL: https://github.com/daohung01/temp-argocd.git
    targetRevision: HEAD
    path: apps/mytenant/nginx-app/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: mytenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
---
# Root Application: STG — deploy nginx app only
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-stg
  namespace: argocd
spec:
  project: labci-stg-apps-project
  source:
    repoURL: https://github.com/daohung01/temp-argocd.git
    targetRevision: HEAD
    path: apps/mytenant/nginx-app/overlays/stg

  destination:
    server: https://kubernetes.default.svc
    namespace: mytenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
