apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

--- 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopify-dev
  namespace: argocd
spec:
  project: dev-project
  source:
    repoURL: https://gitlab....
    targetRevision: main
    path: apps/mytenant/shopify/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mytenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true