apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -stg
namespace: mytenant
images:
  - name: 032794943726.dkr.ecr.ap-southeast-1.amazonaws.com/mytenant/my-web
    newTag: latest
patches:
  - patch: |-
      - op: replace
        path: /spec/hosts
        value:
          - my-web.stg.example.com
      - op: replace
        path: /spec/http/0/route/0/destination/host
        value: my-web-stg.mytenant.svc.cluster.local
    target:
      kind: VirtualService
      name: my-web
      namespace: istio-system
