apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -stg
namespace: mytenant
images:
  - name: 032794943726.dkr.ecr.ap-southeast-1.amazonaws.com/mytenant/my-worker
    newTag: latest
patches:
  - patch: |-
      - op: replace
        path: /data/QUEUE_NAME
        value: "jobs-stg"
    target:
      kind: ConfigMap
      name: my-worker-config
