apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: labci-stg-mytenant-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/daohung01/temp-argocd.git
        revision: main
        directories:
          - path: apps/mytenant/*/overlays/stg
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{index .path.segments 4}}'
    spec:
      project: labci-stg-apps-project

      source:
        repoURL: https://gitlab.labci.com/labci/ops/argocd-deployment/labci/apps-deployments.git
        targetRevision: main
        path: '{{.path.path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: 'mytenant'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        automated:
          prune: true
          selfHeal: false
