apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -stg
namespace: mytenant
images:
  - name: 032794943726.dkr.ecr.ap-southeast-1.amazonaws.com/mytenant/my-app
    newTag: latest
patches:
  - patch: |-
      - op: replace
        path: /spec/hosts
        value:
          - my-app.stg.example.com
      - op: replace
        path: /spec/http/0/route/0/destination/host
        value: my-app-stg.mytenant.svc.cluster.local
    target:
      kind: VirtualService
      name: my-app
      namespace: istio-system
  - patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: "info"
    target:
      kind: ConfigMap
      name: my-app-config
