apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: -stg
namespace: shopify-test
images:
  - name: plugilocrprd.azurecr.io/shopify-prd
    newTag: v18
# patches:
#   - patch: |-
#       - op: replace
#         path: /data/QUEUE_NAME
#         value: "jobs-stg"
#     target:
#       kind: ConfigMap
#       name: my-worker-config
