apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopify
  namespace: shopify-test
  labels:
    app: shopify
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: shopify
  template:
    metadata:
      labels:
        app: shopify
    spec:
      tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
      imagePullSecrets:
        - name: shopify-registry-secret
      #########################################
      # 🔥 Init Container chạy Prisma migrate
      #########################################
      initContainers:
        - name: prisma-migrate
          image: plugilocrprd.azurecr.io/shopify-prd:v18
          command:
            - sh
            - -c
            - npx prisma migrate deploy
          env:
            - name: DATABASE_URL
              value: postgresql://shopify:shopify123@postgres:5432/shopify
      #########################################
      # 🚀 Main App Container
      #########################################
      containers:
        - name: shopify
          image: plugilocrprd.azurecr.io/shopify-prd:v18
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            # DB
            - name: DATABASE_URL
              value: postgresql://shopify:shopify123@postgres:5432/shopify
            # Shopify config
            - name: SHOPIFY_CLI_ACCESS_TOKEN
              value: a294bfc398fe2d4a76be8e5bbdad113e
            - name: SHOPIFY_API_KEY
              value: 093ffa1678f5428e07141d9fbb2018dd
            - name: SHOPIFY_PLUGILO_EXTENSION_ID
              value: b93b168b-9fed-4b04-b2a8-3580525c52a3
            - name: SHOPIFY_API_SECRET
              value: a294bfc398fe2d4a76be8e5bbdad113e
            - name: SHOPIFY_APP_URL
              value: "https://duo-halo-mixing-tuesday.trycloudflare.com"
            - name: SCOPES
              value: "read_products,read_themes,unauthenticated_read_metaobjects,write_products"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
      restartPolicy: Always