apiVersion: v1
kind: Service
metadata:
  name: shopify
  namespace: shopify-test
  labels:
    app: shopify
spec:
  type: LoadBalancer
  selector:
    app: shopify
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 3000
      protocol: TCP