apiVersion: v1
kind: Service
metadata:
  name: my-worker
  namespace: mytenant
  labels:
    app: my-worker
spec:
  selector:
    app: my-worker
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
